name: Deployment

on:
    push:
        branches: ['main']

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x, 22.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run build --if-present
              env:
                  CI: false

    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Add SSH Key
              uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: Deploy Files
              run: |
                  scp -r build/* ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/FZL-ERP-Frontend/
                  ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "sudo systemctl restart nginx"
