name: CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x, 22.x]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - run: npm ci
            - run: npm run build --if-present
            - run: sudo mkdir -p /var/www/FZL-ERP-Frontend # Ensure directory exists
            - run: sudo chown -R $USER:$USER /var/www/FZL-ERP-Frontend # Set permissions (if needed)
            - run: cp -r $GITHUB_WORKSPACE/dist/. /var/www/FZL-ERP-Frontend # Use portable path
